### ISSUE TITLE
packaging el7: zeromq-4.1.4-6.el7.x86_64.rpm with different dependencies on libsodium

### ISSUE THREAD

**Issue by hoonetorg** [saltstack/salt-pack#531]
https://repo.saltstack.com/yum/redhat/7/x86_64/2017.7/ until 2018/04/03 had zeromq-4.1.4-6.el7.x86_64.rpm with a file size of 568796. This version depends on libsodium.so.13 (fullfilled by libsodium-1.0.5-1.el7.x86_64.rpm in this repo from 2018/04/03).

The same package name/version in https://repo.saltstack.com/yum/redhat/7/x86_64/2017.7/  or https://repo.saltstack.com/yum/redhat/7/x86_64/2018.3/ depends on  libsodium.so.23 (fullfilled by libsodium-1.0.16-1.el7.x86_64.rpm in the new repos)

This generates a few problems:
zeromq is not updated on existing machines (due to same name/version of packages)
therefore yum update fails (due to zeromq not updated but libsodium should be updated which removes dependency)
 ```
yum update
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package libsodium.x86_64 0:1.0.5-1.el7 will be updated
--> Processing Dependency: libsodium.so.13()(64bit) for package: zeromq-4.1.4-6.el7.x86_64
---> Package libsodium.x86_64 0:1.0.16-1.el7 will be an update
---> Package salt.noarch 0:2017.7.4-1.el7 will be updated
---> Package salt.noarch 0:2018.3.0-1.el7 will be an update
---> Package salt-minion.noarch 0:2017.7.4-1.el7 will be updated
---> Package salt-minion.noarch 0:2018.3.0-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: zeromq-4.1.4-6.el7.x86_64 (@salt-latest-stable-local)
           Requires: libsodium.so.13()(64bit)
           Removing: libsodium-1.0.5-1.el7.x86_64 (@salt-local)
               libsodium.so.13()(64bit)
           Updated By: libsodium-1.0.16-1.el7.x86_64 (salt-latest-stable-local)
              ~libsodium.so.23()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by dmurphy18** [comment]
@hoonetorg Shall bump release number for zeromq to ensure the issue does not occur in the next point release

**Comment by sevko21** [comment]
any news about the release? Can we find this fix in /yum/redhat saltstack repo?

**Comment by dsteele0301** [comment]
Also looking for an update to this. Our organization is still having issues with CentOS 7 when patching.

`Resolving Dependencies
--> Running transaction check
---> Package libsodium.x86_64 0:1.0.5-1.el7 will be updated
--> Processing Dependency: libsodium.so.13()(64bit) for package: zeromq-4.1.4-6.el7.x86_64
---> Package libsodium.x86_64 0:1.0.16-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: zeromq-4.1.4-6.el7.x86_64 (@repo-saltstack)
           Requires: libsodium.so.13()(64bit)
           Removing: libsodium-1.0.5-1.el7.x86_64 (@repo-saltstack)
               libsodium.so.13()(64bit)
           Updated By: libsodium-1.0.16-1.el7.x86_64 (repo-saltstack)
              ~libsodium.so.23()(64bit)
`

**Comment by epronk** [comment]
Is there a workaround I can orchestrate using salt?

Will there be a new zeromq package in https://repo.saltstack.com/yum/redhat/salt-repo-2017.7-1.el7.noarch.rpm ?

I'll be stuck with salt-master-2017.7.5-1.el7.noarch and salt-minion-2017.7.5-1.el7.noarch for a while and would like to be able to yum update without broken packages.

**Comment by dmurphy18** [comment]
@epronk it is fixed in the upcoming 2017.7.6 point release which should be very soon

**Comment by alias454** [comment]
This is also still an issue when upgrading to v2018.3.0-1.el7
